# Generated by Django 4.0.4 on 2022-05-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('poles', models.IntegerField(default=0)),
                ('titles', models.IntegerField(default=0)),
                ('start_date', models.DateField(verbose_name='date published')),
                ('driver_image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=50)),
                ('symbol', models.ImageField(upload_to='uploads/')),
                ('wins', models.IntegerField(default=0)),
                ('poles', models.IntegerField(default=0)),
                ('boss', models.CharField(max_length=100)),
                ('start_date', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=50)),
                ('laps', models.IntegerField(default=0)),
                ('lapRecord', models.TimeField()),
                ('sector1', models.TimeField()),
                ('sector2', models.TimeField()),
                ('sector3', models.TimeField()),
                ('length', models.IntegerField(default=0)),
                ('layout', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
