# Generated by Django 4.0.4 on 2022-05-10 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BoschWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='BoschWebsite.team'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='start_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='team',
            name='start_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
