# Generated by Django 4.0.4 on 2022-05-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BoschWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='BoschWebsite.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='boss_image',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='team',
            name='titles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='titles_constructors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='titles_drivers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name_text',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='symbol',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='track',
            name='layout',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='track',
            name='length',
            field=models.FloatField(default=0),
        ),
    ]
