# Generated by Django 4.0.4 on 2022-05-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoschWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='start_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='team',
            name='start_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
